install.ps1
This is the start of the script for doing an system-agent install on Windows. The basics are there and it follows the same structure as the Bash version. Most of it has had some testing conducted and until we have an actual windows build it will be difficult to fully test.
=> Creating a Windows PowerShell installation script for the system agent.

install.sh
=> Add an explicit rancher connection check

install.sh
While unit testing I hit the GH rate limit.
=> Use a more recent fallback version

package/suc/run.sh
=> Clean up SUC run script

install.sh
https://github.com/rancher/rancher/issues/32786
=> add a if-not-root-then-fail check to the install script

install.sh
https://github.com/rancher/rancher/issues/32695
=> Add --taints as an option

install.sh
https://github.com/rancher/rancher/issues/32875
=> Add missing flags

install.sh
https://github.com/rancher/system-agent/issues/18
=> Change to using RNG instead of machine-id for cattle-id

pkg/k8splan/watcher.go
https://github.com/rancher/system-agent/issues/20
=> Add retry logic to always retry unless a 409 is received

install.sh
https://github.com/rancher/system-agent/issues/24
=> Trim generated cattle-id to 63 characters

pkg/applyinator/applyinator.go
https://github.com/rancher/system-agent/issues/28
=> Add empty working directory support

install.sh, main.go, pkg/applyinator/applyinator.go, pkg/config/config.go
https://github.com/rancher/system-agent/issues/29
https://github.com/rancher/system-agent/issues/30
=> Make config file permissions more secure; disable local plan support by default

install.sh
=> Use /usr/local/bin instead of /usr/bin

install.sh
=> Update install.sh to use for validating rancher connection

pkg/k8splan/watcher.go
=> Perform safer secret processing

pkg/k8splan/watcher.go
=> Initialize probeStatuses if not already

pkg/k8splan/watcher.go
=> Check probes regardless of resource version

pkg/k8splan/watcher.go
github.com/rancher/rancher/issues/33878
=> Remove CA data if initial connection attempt fails and provide more context when unable to connect to Rancher

pkg/k8splan/watcher.go
https://github.com/rancher/rancher/issues/34027
=> Don't apply if resource version is incorrect

install.sh
In order to make https://github.com/rancher/rancher/issues/34015 doable
=> Check to see if CA is actually required

pkg/config/config.go, pkg/config/config_unix.go, pkg/config/config_windows.go, scripts/version
We need to take this step to start working on getting the system agent running on Windows.
Signed-off-by: Jamie Phillips <jamie.phillips@suse.com>
=> Adding Windows builds and compiles.

pkg/applyinator/applyinator.go, pkg/k8splan/watcher.go, scripts/default
https://github.com/rancher/system-agent/issues/49
=> Add failure handling to system-agent

pkg/config/config.go, pkg/config/config_unix.go, pkg/image/util.go, pkg/prober/prober.go
Signed-off-by: Brian Downs <brian.downs@gmail.com>
=> update type assertion to prevent panic

go.mod, go.sum, pkg/applyinator/file.go, pkg/applyinator/file_unix.go, pkg/applyinator/file_windows.go, pkg/config/config.go, pkg/config/config_unix.go, pkg/config/config_windows.go, pkg/image/util.go, pkg/image/util_unix.go, pkg/image/util_windows.go
File permissions on Windows don't behave the same as on Linux so those needed adjusting. 
Wharfie wasn't passing the OS information so the correct image wasn't being pulled for Windows and it was required to be bumped to address issues with extracting files from Windows images on Windows.
=> Fixes various Windows specific bugs discovered during test.

.drone.yml
Add s390x support to rancher/rancher
Part of https://github.com/rancher/rancher/issues/35501
=> Add s390x arch

pkg/applyinator/applyinator.go
Follow up of: https://github.com/rancher/system-agent/pull/68
=> Set default period to 600 seconds for periodic instructions

pkg/applyinator/applyinator.go
Follow up of https://github.com/rancher/system-agent/pull/68
=> Only set LastRunTime if periodic output was successful

pkg/applyinator/applyinator.go
Rename lastRunTime to lastSuccessfulRunTime to be more accurate for periodic instructions
Continuation of https://github.com/rancher/system-agent/pull/72
=> Rename lastRunTime to lastSuccessfulRunTime to be more accurate for periodic instructions

install.sh
=> Set default log level to info

pkg/applyinator/applyinator.go
https://github.com/rancher/system-agent/issues/74
=> Only write applied plan contents if the plan actually changes

pkg/applyinator/applyinator.go
=> create directory for applied plans before listing the directory

pkg/applyinator/applyinator.go
=> Move log messages around to prevent unnecessarily redundant messages

pkg/applyinator/applyinator.go
=> Correctly pick up on failed apply

pkg/applyinator/applyinator.go
https://github.com/rancher/rancher/issues/36483
=> Increase max cooldown duration, tidy applyinator, and add debug messages

go.sum, pkg/prober/prober_windows.go
Issue: https://github.com/rancher/rancher/issues/37628
Passing certContext to the deferred function ensures that the value will
be taken at that point. The issue is that it is nil when the deferred
function is called.
This change will capture the variable so its real value is passed
=> Fix nil-pointer dereference on windows context

pkg/k8splan/watcher.go
* https://github.com/rancher/windows/issues/161
=> This fixes the TLS handshake on Windows.

pkg/k8splan/watcher.go
https://github.com/rancher/rancher/issues/41200
Add error handling logic that handles edge cases to force the system-agent to restart if we encounter non-transient errors. Disallow the K8s watcher from manipulating a secret when the UID changes.
=> Handle errors through Fatalf, forcing cache rehydration

install.sh
I've introduced support for systems that utilise transactional-update, e.g. SLE Micro, openSUSE Leap Micro, and openSUSE MicroOS. On these systems the filesystem is either read-only, or is snapshot based, which means that the original install locations for CATTLE_AGENT_BIN_PREFIX and CATTLE_AGENT_VAR_DIR are not typically writeable, depending on whether transactional-update is being called.
This patch checks to see whether the system is using transactional-update and if so, adapts the install locations and/or calls transactional-update to make the appropriate changes.
This patch set supports both manually executing the script, i.e. a Rancher "custom" installation, and initiating the deployment via ignition/combustion (where transactional-update is called automatically).
=> Add support for transactional-update based systems

pkg/applyinator/applyinator.go
Check that last successful run time is not an empty string before trying to parse it.
* for https://github.com/rancher/rancher/issues/40808
=> Fix repeated time parse error on probes that have not yet run successfully

package/Dockerfile.suc, package/suc/run.sh
https://github.com/rancher/rancher/issues/45038
=> Add support for CATTLE_AGENT_VAR_DIR in suc plan

install.sh
=> [45815] sle micro 6

install.sh
https://github.com/rancher/rancher/issues/46775
=> Add default fallback values to PATH

.github/workflows/release.yaml
- Add GitHub App token generation and dispatch job for System Agent Upgrade workflow.
- https://github.com/rancher/rancher/issues/47179
=> Add GitHub App token generation and dispatch job for System Agent Upgrade workflow.

.github/workflows/release.yaml
- added the owner setting required to dispatch a workflow for create app token step
- added release-v2.11 branch as well in the target-branches list
=> fix dispatch workflow
