rancher/system-agent

install.sh

In development situations we don't want to mirror the agent
binaries. It ends up being easier to be able to control whether
or not the binaries should be pulled form rancher by setting
CATTLE_AGENT_BINARY_BASE_URL.

Don't set CATTLE_AGENT_BINARY_URL from CATTLE_SERVER

---

pkg/k8splan/watcher.go
pkg/prober/prober.go

Use URL instead of path for http get action and change probe-period to probe-period-seconds

Use URL instead of path for http get action and change probe-period

---

pkg/k8splan/watcher.go

https://github.com/rancher/system-agent/issues/33

Check K8s cluster is healthy before proceeding to watch for remote K8s plans

---

install.sh
package/suc/run.sh

The install script only looked for proxy environment variables in the
VM's environment. Passing these variables via agent args was not
supported. Therefore, if a user tried to pass proxy variables via agent
args, then the cluster-agent would see them but none of the system-agent
commands would.
Now, if the user passes these variables via agent args (which are
included at the top of the install.sh file), then the install script
will see them and include them in the environment file.
Issue:
https://github.com/rancher/rancher/issues/32633

Look for proxy environment variables in script

---

install.sh

A previous change added CIDR support in the NO_PROXY environment variable for
curl. That change mistakenly added an equal-sign. This change removes the
equal-sign.
Issue:
https://github.com/rancher/rancher/issues/35913

Fix --noproxy curl flag

---

pkg/applyinator/applyinator.go
pkg/k8splan/watcher.go

https://github.com/rancher/rancher/issues/37296
This PR adds `max-retries` support and adds functionality to cooldown application of periodic instructions if they are failing.

add periodic instruction cooldown 

---

pkg/prober/prober.go
pkg/prober/prober_unix.go
pkg/prober/prober_windows.go

Move the get/create of a root CA cert store into OS dependent functions
Fixes https://github.com/rancher/system-agent/issues/83
Unblocks https://github.com/rancher/windows/issues/161
Windows does not support x509.SystemCertPool() in <go1.18. This PR implements a workaround to load the System Cert Store on Windows nodes.
This is adapted from the following workaround: https://github.com/golang/go/issues/16736#issuecomment-540373689
Error seen on Windows machines:
`Message : error loading system cert pool for probe (kubelet): crypto/x509: system root pool is not available on Windows`
Since <go1.18 on Windows cannot load the root CA cert store, this PR leverages syscalls to load the certificate context from the Root CA cert store and then create a new x509 cert pool that contains the Root …

add windows support for root CA cert stores

---

install.sh
package/suc/run.sh

The uninstall script was added to the suc image, but not the script which runs the install script and copies the assets.
Added the uninstall script to the script to copy assets.
I used a QA provisioned airgap setup with a custom suc image with my changed included to test the issue, which worked.
Upgrade rke2/k3s custom cluster from 1.23 -> 1.24 after this PR has been merged, system-agent has been released, and the version has been bumped in rancher.

Reuse version if found for binary, and add uninstall to suc entrypoint

---

pkg/k8splan/watcher.go

A change was made [here](https://github.com/rancher/system-agent/pull/89) to fix TLS on windows. From the text of `utilnet.SetTransportDefaults`:
> // SetTransportDefaults applies the defaults from http.DefaultTransport
// for the Proxy, Dial, and TLSHandshakeTimeout fields if unset
This breaks proxy setups in rancher v2.6.7 and v2.6.8. The following is a version matrix of which system-agent version belongs to which rancher version:
|rancher|system agent|
|---|---|
|v2.6.8|v0.2.10|
|v2.6.7|v0.2.10|
|v2.6.6|v0.2.7|
|v2.6.5|v0.2.7|
|v2.6.4|v0.2.3|
|v2.6.3|v0.1.1|
This has also been tested on Windows, which appears to have other issues, mainly with probes, but it makes it past the system agent install now.

Add proxy to validate rest config

---

pkg/k8splan/watcher.go

#39066 @snasovich Despite the docs, proxies don't actually work without this.

Add back TLSClientConfig to transport

---

package/suc/run.sh

ref: https://github.com/harvester/harvester/issues/2821
When `run.sh` script fails, it leaves a temporary folder. Try to clean it up when the script exits.

fix(run.sh): cleanup temp folder when script fail

---

package/Dockerfile.suc

This fixes an issue where the `kubectl` being downloaded in the image is actually an XML document for a 404 error code. The fix is simply to transform `aarch64` to `arm64` when necessary. Additional protections are added to avoid this issue in the future:
* Use `curl -f` to fail on non 2xx status codes
* Run `kubectl version --client` to make sure the binary works as expected

Use `kubectl version` to make sure the downloaded binary works

---

pkg/k8splan/watcher.go

https://github.com/rancher/system-agent/issues/113

Retry update with latest secret if plan still matches the applied plan

---

.drone.yml
install.sh
main.go
pkg/applyinator/applyinator.go
pkg/config/config.go
scripts/version

https://github.com/rancher/rancher/issues/43658
This PR adds interlocks to the system-agent which are used to indicate whether the install script and applyinator should continue.
The first interlock `restart-pending` indicates to the system-agent that a restart is pending per the install script, and disallows the applyinator from starting to apply a plan when a restart is pending.
The second interlock `applyinator-active` indicates to the install script that the applyinator is currently reconciling a plan and should not restart the system-agent.
The `restart-pending` interlock has a timeout feature built into the system-agent which allows the system-agent to ignore the pending restart after 5 minutes, which can be the case when the install script quits prematurely.

Add interlocks to ensure operations are not interrupted

---

install.sh

https://github.com/rancher/rancher/issues/43991
This PR fixes an issue where if maximum retries are met attempting to download the rancher2_connection_info.json, the script continues with invalid data in that file causing the rancher-system-agent to fail to start.  This change cleans up the errant json file and exits the installer instead of continuing to setup a service doomed for failure.
Ref. SUSE Support case #01054437

Cleanup and exit if cannot download valid connection info.

---

install.sh
main.go
pkg/k8splan/watcher.go

https://github.com/rancher/rancher/issues/45581
Add support for the environment variables `CATTLE_AGENT_STRICT_VERIFY` and `STRICT_VERIFY` to lock the system-agent to only connecting to the provide `cacerts`

Add support for `CATTLE_AGENT_STRICT_VERIFY` | `STRICT_VERIFY` env vars

---

package/Dockerfile
package/Dockerfile.suc

Version bump for Alpine and Kubectl:
- Alpine - `3.18.3` -> `3.18`
- Kubectl - `v1.24.0` -> `v1.27.10` (match the current K8s version in `go.mod`)

Version bump for Alpine and Kubectl

---

go.mod
go.sum

Issue: https://github.com/rancher/rancher/issues/46090
[rancher/wharfile v0.6.6](https://github.com/rancher/wharfie/releases/tag/v0.6.6) adds the support for bare hostname as endpoint
We bump wharfile to v0.6.6 so that the following mirror configuration, where the endpoint url does not contain schema,  will work:
```
mirrors:
'*':
endpoint:
- registry.hub.docker.com
```

Update module github.com/rancher/wharfie to v0.6.6

---

Dockerfile.dapper
package/Dockerfile
package/Dockerfile.suc

Issues:
* https://github.com/rancher/rancher/issues/46098
* https://github.com/rancher/rancher/issues/46621
* https://github.com/rancher/rancher/issues/46623
~Note that `kubectl` is also being bumped to `v1.28.10` as the previously used `v1.27` is EOL.~ - already bumped in another PR

Change base images to `bci-micro`

---

package/Dockerfile

Follow up to https://github.com/rancher/system-agent/pull/169 as the images would not build due to the lack of `zypper` in the `bci-micro` image

[Followup] Change base images to `bci-micro`

---

package/Dockerfile.suc

Follow up to https://github.com/rancher/system-agent/pull/169 and https://github.com/rancher/system-agent/pull/194 as the SUC image was erroring out

[Followup 2] Change base images to `bci-micro`

---

.github/workflows/ci-on-pull-request.yaml
go.mod
go.sum
pkg/applyinator/file_test.go
pkg/applyinator/file_unix.go
pkg/applyinator/file_windows.go

This PR closes the gap between how files are created on Linux and Windows. It also adds unit tests around file permissions, as well as updates CI to run these tests on both Linux and Windows. 
Note: This unit test does not compile properly on arm, and I can't determine why. Testing the CI on my fork repeatedly resulted in the below error. Because of this, I added a build tag to exclude this unit test on arm. I'm not aware of any differences between file creation and permissions between the two architectures, but if we feel strongly about including this test on arm I can continue to look into the error. But ultimately, for linux, this unit test is covering functionality was added to this repo ~3 years ago.
```  
fork/exec /tmp/go-build3394345592/b1239/applyinator.test: exec format error …
```

Update Windows Files

---

pkg/applyinator/applyinator.go
pkg/k8splan/watcher.go

Issue: https://github.com/rancher/rancher/issues/42458, RFC-13
This PR adds the `ResetFailureCountOnStartup` field to the `OneTimeInstruction` struct. If this field is set to true, during the [initial force application of the one-time instruction set ](https://github.com/rancher/system-agent/blob/7ad21ffbe9273d33d28fbf17249e949fdc6d8610/pkg/k8splan/watcher.go#L214-L218) the plans `failure-count` and `applied-checksum` fields will be reset. This ensures that the `max-failures` field is always respected, even if the plan had previously succeeded when executed by a prior instance of the system-agent. Due to the fact that the `failure-count` and `applied-checksum` fields are stored at the top level (and not as an attribute of the `plan` key) this will occur if any of the one time instructions …

Add ResetFailureCountOnServiceRestart

---

pkg/k8splan/watcher.go

This PR addresses issue https://github.com/rancher/rancher/issues/48916 by implementing retry logic for one-time instructions.
- Added retry logic using `retry.OnError` for one-time instruction execution
Manually tested.
Logs: 
```
root@ip-x.x.x.x:/home/ubuntu# journalctl -fu rancher-system-agent.service
rancher-system-agent[82604]: time="2025-03-26T23:13:40Z" level=info msg="Rancher System Agent version 15b7568 (15b7568) is starting"
rancher-system-agent[82604]: time="2025-03-26T23:13:40Z" level=info msg="Using directory /var/lib/rancher/agent/work for work"
rancher-system-agent[82604]: time="2025-03-26T23:13:40Z" level=info msg="Starting remote watch of plans"
rancher-system-agent[82604]: time="2025-03-26T23:13:40Z" level=info msg="Initial connection to Kubernetes cluster failed with …
```

fix: add retry logic for one time instruction

---

pkg/applyinator/file_test.go

This can just get merged whenever, it's just to enable these tests to run locally. I've confirmed they work both with `go test ./...` and `make test`.

Get UID/GID for current user in write file_test.go

---

.github/workflows/ci-on-pull-request.yaml

GHA is dropping Windows 2019 support on June 30th, so we can't continue using it in our PR CI. I kept the 2022 step, so we aren't really losing much test coverage anyway.

Drop windows 2019 when running PR CI
